"""empty message

Revision ID: 5f8c04e7af1e
Revises: e81a3408197b
Create Date: 2025-04-25 14:53:01.590349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8c04e7af1e'
down_revision = 'e81a3408197b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tasks',
    sa.Column('task_id', sa.Integer(), nullable=False,autoincrement=True),
    sa.Column('task_name', sa.String(length=45), nullable=True),
    sa.Column('task_assignee', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('user_id')

    op.create_table('task_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('assignee', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='task_master_pkey')
    )
    op.drop_table('Tasks')
    # ### end Alembic commands ###
