"""empty message

Revision ID: 8ae793cfd702
Revises: 20cd8fc124fb
Create Date: 2025-05-06 15:03:17.220698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae793cfd702'
down_revision = '20cd8fc124fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_due_date', sa.Date(), nullable=True))
        batch_op.drop_constraint('Tasks_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Tasks_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('task_due_date')

    # ### end Alembic commands ###
