"""empty message
 
 Revision ID: e81a3408197b
 Revises: 7fe368b7bced
 Create Date: 2025-04-24 22:56:47.451433
 
 """
from alembic import op
import sqlalchemy as sa
 
 
 # revision identifiers, used by Alembic.
revision = 'e81a3408197b'
down_revision = None
branch_labels = None
depends_on = None
 
 
def upgrade():
     # ### commands auto generated by Alembic - please adjust! ###
     with op.batch_alter_table('task_master', schema=None) as batch_op:
         batch_op.add_column(sa.Column('name', sa.String(length=45), nullable=True))
         batch_op.add_column(sa.Column('assignee', sa.String(length=45), nullable=True))
         batch_op.drop_column('task')
 
     # ### end Alembic commands ###
 
 
def downgrade():
     # ### commands auto generated by Alembic - please adjust! ###
     with op.batch_alter_table('task_master', schema=None) as batch_op:
         batch_op.add_column(sa.Column('task', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
         batch_op.drop_column('assignee')
         batch_op.drop_column('name')
 
     # ### end Alembic commands ###