
services:
  web:
    image: task_master:0.1.2
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://admin:admin@db:5432/crud_app
    volumes:
      - .:/app
      - ./templates:/app/templates 
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=crud_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: