services:
  web:
    image: task_master:0.1.3
    ports:
      - "5000:5000"
    env_file: "webapp.env"
    volumes:
      - .:/app
      - ./templates:/app/templates 
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=crud_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: